from django.db import models

# Create your models here.


class Listings(models.Model):
    address = models.CharField(max_length=255)
    adjacent_suburb_ids = models.TextField()
    adjacent_suburb_names = models.TextField()
    agency = models.TextField()
    agency_reference = models.TextField()
    amenities = models.TextField()
    as_at = models.TextField()
    available_from = models.TextField()
    bathrooms = models.SmallIntegerField()
    bedrooms = models.SmallIntegerField()
    best_contact_time = models.TextField()
    category = models.TextField()
    category_path = models.TextField()
    district = models.TextField()
    district_id = models.IntegerField()
    end_date = models.TextField()
    geographic_location = models.TextField()
    has_embedded_video = models.BooleanField()
    has_gallery = models.BooleanField()
    ideal_tenant = models.TextField()
    is_bold = models.BooleanField()
    is_classified = models.BooleanField()
    is_featured = models.BooleanField()
    is_highlighted = models.BooleanField()
    is_super_featured = models.BooleanField()
    listing_group = models.TextField()
    listing_id = models.TextField()
    listing_length = models.TextField()
    max_tenants = models.SmallIntegerField()
    note_date = models.TextField()
    open_homes = models.TextField()
    parking = models.TextField()
    pets_okay = models.BooleanField()
    photo_urls = models.TextField()
    picture_href = models.URLField()
    price_display = models.TextField()
    property_id = models.TextField()
    property_type = models.TextField()
    region = models.TextField()
    region_id = models.IntegerField()
    rent_per_week = models.DecimalField(max_digits=10, decimal_places=2)
    reserve_state = models.IntegerField()
    smokers_okay = models.IntegerField()
    start_date = models.TextField()
    start_price = models.IntegerField()
    suburb = models.TextField()
    suburb_id = models.IntegerField()
    title = models.TextField()
    whiteware = models.TextField()
