# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 05:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adjacent_Suburb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id_agency', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('fax', models.CharField(max_length=30, null=True)),
                ('is_licenced_property', models.NullBooleanField()),
                ('is_real_estate', models.NullBooleanField()),
                ('phone', models.CharField(max_length=30, null=True)),
                ('website', models.URLField(null=True)),
                ('last_updated', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Agency_Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo1', models.URLField(null=True)),
                ('logo2', models.URLField(null=True)),
                ('brand_background_color', models.CharField(max_length=20, null=True)),
                ('brand_stroke_color', models.CharField(max_length=20, null=True)),
                ('brand_text_color', models.CharField(max_length=20, null=True)),
                ('brand_large_banner', models.URLField(null=True)),
                ('brand_disable_banner', models.NullBooleanField()),
                ('brand_office_location', models.CharField(max_length=100)),
                ('last_updated', models.DateTimeField()),
                ('id_agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.Agency')),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id_agent', models.IntegerField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=50, null=True)),
                ('mobile', models.CharField(max_length=20, null=True)),
                ('office_phone', models.CharField(max_length=20, null=True)),
                ('photo', models.URLField(null=True)),
                ('url_slug', models.CharField(max_length=50, null=True)),
                ('last_updated', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Agent_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField()),
                ('id_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.Agent')),
            ],
        ),
        migrations.CreateModel(
            name='Current_Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Detail_Main_Rental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenities', models.TextField(null=True)),
                ('available_from', models.DateTimeField(null=True)),
                ('bathrooms', models.PositiveSmallIntegerField(null=True)),
                ('bedrooms', models.PositiveSmallIntegerField(null=True)),
                ('best_contact_time', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('ideal_tenant', models.TextField(null=True)),
                ('listing_group', models.CharField(max_length=30, null=True)),
                ('max_tenants', models.SmallIntegerField(null=True)),
                ('parking', models.TextField(null=True)),
                ('pets_okay', models.NullBooleanField()),
                ('price_display', models.CharField(max_length=30, null=True)),
                ('property_id', models.CharField(max_length=20, null=True)),
                ('property_type', models.CharField(max_length=20, null=True)),
                ('smokers_okay', models.NullBooleanField()),
                ('start_date', models.DateTimeField(null=True)),
                ('start_price', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('title', models.CharField(max_length=100, null=True)),
                ('rent_per_week', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('whiteware', models.CharField(max_length=255, null=True)),
                ('last_updated', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Detail_Main_Residential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenities', models.TextField(null=True)),
                ('available_from', models.DateTimeField(null=True)),
                ('bathrooms', models.PositiveSmallIntegerField(null=True)),
                ('bedrooms', models.PositiveSmallIntegerField(null=True)),
                ('best_contact_time', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('ideal_tenant', models.TextField(null=True)),
                ('listing_group', models.CharField(max_length=30, null=True)),
                ('max_tenants', models.SmallIntegerField(null=True)),
                ('parking', models.TextField(null=True)),
                ('pets_okay', models.NullBooleanField()),
                ('price_display', models.CharField(max_length=30, null=True)),
                ('property_id', models.CharField(max_length=20, null=True)),
                ('property_type', models.CharField(max_length=20, null=True)),
                ('smokers_okay', models.NullBooleanField()),
                ('start_date', models.DateTimeField(null=True)),
                ('start_price', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('title', models.CharField(max_length=100, null=True)),
                ('rent_per_week', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('whiteware', models.CharField(max_length=255, null=True)),
                ('last_updated', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id_district', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('last_updated', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id_listing', models.IntegerField(primary_key=True, serialize=False)),
                ('listing_type', models.CharField(max_length=20)),
                ('is_current', models.NullBooleanField()),
                ('data_source', models.CharField(max_length=20)),
                ('job_run_datetime', models.DateTimeField()),
                ('last_updated', models.DateTimeField()),
                ('id_agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.Agency')),
            ],
        ),
        migrations.CreateModel(
            name='Listing_Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, null=True)),
                ('latitude', models.CharField(max_length=20)),
                ('longitude', models.CharField(max_length=20)),
                ('easting', models.CharField(max_length=20)),
                ('northing', models.CharField(max_length=20)),
                ('last_updated', models.DateTimeField()),
                ('id_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.Listing')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id_location', models.IntegerField(primary_key=True, serialize=False)),
                ('last_updated', models.DateTimeField()),
                ('id_district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.District')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_key', models.CharField(max_length=20)),
                ('last_updated', models.DateTimeField()),
                ('id_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.Listing')),
            ],
        ),
        migrations.CreateModel(
            name='Photo_Type_Helper',
            fields=[
                ('id_photo_type', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('url_name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=50, null=True)),
                ('last_updated', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('last_updated', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Suburb',
            fields=[
                ('id_suburb', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('last_updated', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Tm_Detail_Sub_Rental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_reference', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=30, null=True)),
                ('category_path', models.CharField(max_length=100, null=True)),
                ('has_embedded_video', models.NullBooleanField()),
                ('has_gallery', models.NullBooleanField()),
                ('is_bold', models.NullBooleanField()),
                ('is_featured', models.NullBooleanField()),
                ('is_highlighted', models.NullBooleanField()),
                ('is_super_featured', models.NullBooleanField()),
                ('listing_length', models.CharField(max_length=20, null=True)),
                ('note_date', models.DateTimeField(null=True)),
                ('reserve_state', models.SmallIntegerField(null=True)),
                ('is_boosted', models.NullBooleanField()),
                ('last_updated', models.DateTimeField()),
                ('id_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.Listing')),
            ],
        ),
        migrations.CreateModel(
            name='Tm_Detail_Sub_Residential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_reference', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=30, null=True)),
                ('category_path', models.CharField(max_length=100, null=True)),
                ('has_embedded_video', models.NullBooleanField()),
                ('has_gallery', models.NullBooleanField()),
                ('is_bold', models.NullBooleanField()),
                ('is_featured', models.NullBooleanField()),
                ('is_highlighted', models.NullBooleanField()),
                ('is_super_featured', models.NullBooleanField()),
                ('listing_length', models.CharField(max_length=20, null=True)),
                ('note_date', models.DateTimeField(null=True)),
                ('reserve_state', models.SmallIntegerField(null=True)),
                ('is_boosted', models.NullBooleanField()),
                ('last_updated', models.DateTimeField()),
                ('id_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.Listing')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='id_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.Region'),
        ),
        migrations.AddField(
            model_name='location',
            name='id_suburb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.Suburb'),
        ),
        migrations.AddField(
            model_name='listing_location',
            name='id_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.Location'),
        ),
        migrations.AddField(
            model_name='detail_main_residential',
            name='id_listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.Listing'),
        ),
        migrations.AddField(
            model_name='detail_main_rental',
            name='id_listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.Listing'),
        ),
        migrations.AddField(
            model_name='current_listing',
            name='id_current_listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.Listing'),
        ),
        migrations.AddField(
            model_name='agent_detail',
            name='id_listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.Listing'),
        ),
        migrations.AddField(
            model_name='adjacent_suburb',
            name='id_adjacent_suburb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.Suburb'),
        ),
        migrations.AddField(
            model_name='adjacent_suburb',
            name='id_listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.Listing'),
        ),
    ]
