# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-20 13:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_auto_20170519_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='id_agency_tm',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='agency_brand',
            name='id_agency_tm',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='district',
            name='id_district_tm',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='agent',
            field=models.ManyToManyField(through='analytics.Agent_Detail', to='analytics.Agent'),
        ),
        migrations.AddField(
            model_name='listing',
            name='id_listing_tm',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='valid_from',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 20, 23, 32, 37, 426334)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='valid_to',
            field=models.DateTimeField(default=datetime.date(2099, 1, 1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='region',
            name='id_region_tm',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suburb',
            name='id_suburb_tm',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agency',
            name='id_agency',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='agency_brand',
            name='id_agency',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='analytics.Agency'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='id_agent',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='detail_main_rental',
            name='id_listing',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='analytics.Listing'),
        ),
        migrations.AlterField(
            model_name='detail_main_residential',
            name='id_listing',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='analytics.Listing'),
        ),
        migrations.AlterField(
            model_name='district',
            name='id_district',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='listing',
            name='id_agency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='analytics.Agency'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='id_listing',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='listing_location',
            name='id_listing',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='analytics.Listing'),
        ),
        migrations.AlterField(
            model_name='location',
            name='id_location',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='region',
            name='id_region',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='suburb',
            name='id_suburb',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tm_detail_sub_rental',
            name='id_listing',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='analytics.Listing'),
        ),
        migrations.AlterField(
            model_name='tm_detail_sub_residential',
            name='id_listing',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='analytics.Listing'),
        ),
    ]
