# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-20 13:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_auto_20170520_2333'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ('id_listing', 'id_listing_tm')},
        ),
    ]
