# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 13:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_auto_20170520_2353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={},
        ),
        migrations.RemoveField(
            model_name='agency_brand',
            name='id',
        ),
        migrations.RemoveField(
            model_name='detail_main_rental',
            name='id',
        ),
        migrations.RemoveField(
            model_name='detail_main_residential',
            name='id',
        ),
        migrations.RemoveField(
            model_name='listing_location',
            name='id',
        ),
        migrations.RemoveField(
            model_name='tm_detail_sub_rental',
            name='id',
        ),
        migrations.RemoveField(
            model_name='tm_detail_sub_residential',
            name='id',
        ),
        migrations.AlterField(
            model_name='adjacent_suburbs',
            name='id_suburb',
            field=models.ForeignKey(db_column='id_suburb', on_delete=django.db.models.deletion.CASCADE, to='analytics.Suburb'),
        ),
        migrations.AlterField(
            model_name='agency_brand',
            name='id_agency',
            field=models.OneToOneField(db_column='id_agency', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='analytics.Agency'),
        ),
        migrations.AlterField(
            model_name='agent_detail',
            name='id_agent',
            field=models.ForeignKey(db_column='id_agent', on_delete=django.db.models.deletion.CASCADE, to='analytics.Agent'),
        ),
        migrations.AlterField(
            model_name='agent_detail',
            name='id_listing',
            field=models.ForeignKey(db_column='id_listing', on_delete=django.db.models.deletion.CASCADE, to='analytics.Listing'),
        ),
        migrations.AlterField(
            model_name='current_listing',
            name='id_current_listing',
            field=models.ForeignKey(db_column='id_agency', on_delete=django.db.models.deletion.CASCADE, to='analytics.Listing'),
        ),
        migrations.AlterField(
            model_name='detail_main_rental',
            name='id_listing',
            field=models.OneToOneField(db_column='id_listing', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='analytics.Listing'),
        ),
        migrations.AlterField(
            model_name='detail_main_residential',
            name='id_listing',
            field=models.OneToOneField(db_column='id_listing', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='analytics.Listing'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='id_agency',
            field=models.ForeignKey(db_column='id_agency', null=True, on_delete=django.db.models.deletion.CASCADE, to='analytics.Agency'),
        ),
        migrations.AlterField(
            model_name='listing_location',
            name='id_listing',
            field=models.OneToOneField(db_column='id_listing', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='analytics.Listing'),
        ),
        migrations.AlterField(
            model_name='listing_location',
            name='id_location',
            field=models.ForeignKey(db_column='id_location', on_delete=django.db.models.deletion.CASCADE, to='analytics.Location'),
        ),
        migrations.AlterField(
            model_name='location',
            name='id_district',
            field=models.ForeignKey(db_column='id_district', on_delete=django.db.models.deletion.CASCADE, to='analytics.District'),
        ),
        migrations.AlterField(
            model_name='location',
            name='id_region',
            field=models.ForeignKey(db_column='id_region', on_delete=django.db.models.deletion.CASCADE, to='analytics.Region'),
        ),
        migrations.AlterField(
            model_name='location',
            name='id_suburb',
            field=models.ForeignKey(db_column='id_suburb', on_delete=django.db.models.deletion.CASCADE, to='analytics.Suburb'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='id_listing',
            field=models.ForeignKey(db_column='id_listing', on_delete=django.db.models.deletion.CASCADE, to='analytics.Listing'),
        ),
        migrations.AlterField(
            model_name='tm_detail_sub_rental',
            name='id_listing',
            field=models.OneToOneField(db_column='id_listing', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='analytics.Listing'),
        ),
        migrations.AlterField(
            model_name='tm_detail_sub_residential',
            name='id_listing',
            field=models.OneToOneField(db_column='id_listing', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='analytics.Listing'),
        ),
    ]
